version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pdf"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12ita30b3l0g"
s3_prefix = "pdf"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
